### ISSUE TITLE
cannot install from windows

### ISSUE THREAD

**Issue by dridk** [nspies/genomeview#11]
From windows 7

  ```
    pip install genomeview
       Collecting genomeview
  Using cached https://files.pythonhosted.org/packages/81/34/db88cf0c01f9dc78da709e55ae6c7f271608e19f1ec72c851cd85926bf0a/genomeview-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    '.' n'est pas reconnu en tant que commande interne
    ou externe, un programme ex▒cutable ou un fichier de commandes.
    '.' n'est pas reconnu en tant que commande interne
    ou externe, un programme ex▒cutable ou un fichier de commandes.
    # pysam: no cython available - using pre-compiled C
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\WINDOWS\TEMP\Mxt105\tmp\easy_install-tkfkv61c\pysam-0.15.1\setup.py", line 223, in <module>
      File "C:\WINDOWS\TEMP\Mxt105\tmp\easy_install-tkfkv61c\pysam-0.15.1\setup.py", line 69, in run_make_print_config
      File "c:\sacha\software\python37\lib\subprocess.py", line 376, in check_output
        **kwargs).stdout
      File "c:\sacha\software\python37\lib\subprocess.py", line 453, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\sacha\software\python37\lib\subprocess.py", line 756, in __init__
        restore_signals, start_new_session)
      File "c:\sacha\software\python37\lib\subprocess.py", line 1155, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] Le fichier sp▒cifi▒ est introuvable

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\WINDOWS\TEMP\Mxt105\tmp\pip-install-cllxgs93\genomeview\setup.py", line 48, in <module>
        python_requires=">=3.3"
      File "c:\sacha\software\python37\lib\site-packages\setuptools\__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\sacha\software\python37\lib\site-packages\pkg_resources\__init__.py", line 770, in resolve
        replace_conflicting=replace_conflicting
      File "c:\sacha\software\python37\lib\site-packages\pkg_resources\__init__.py", line 1053, in best_match
        return self.obtain(req, installer)
      File "c:\sacha\software\python37\lib\site-packages\pkg_resources\__init__.py", line 1065, in obtain
        return installer(requirement)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\command\easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\command\easy_install.py", line 884, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\command\easy_install.py", line 1152, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\command\easy_install.py", line 1138, in run_setup
        run_setup(setup_script, args)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "c:\sacha\software\python37\lib\contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\sacha\software\python37\lib\contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\sacha\software\python37\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\WINDOWS\TEMP\Mxt105\tmp\easy_install-tkfkv61c\pysam-0.15.1\setup.py", line 223, in <module>
      File "C:\WINDOWS\TEMP\Mxt105\tmp\easy_install-tkfkv61c\pysam-0.15.1\setup.py", line 69, in run_make_print_config
      File "c:\sacha\software\python37\lib\subprocess.py", line 376, in check_output
        **kwargs).stdout
      File "c:\sacha\software\python37\lib\subprocess.py", line 453, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\sacha\software\python37\lib\subprocess.py", line 756, in __init__
        restore_signals, start_new_session)
      File "c:\sacha\software\python37\lib\subprocess.py", line 1155, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] Le fichier sp▒cifi▒ est introuvable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\WINDOWS\TEMP\Mxt105\tmp\pip-install-cllxgs93\genomeview\
```

**Comment by nspies** [comment]
This looks like a known limitation of the required pysam library: https://github.com/pysam-developers/pysam/issues/575
