### ISSUE TITLE
pip install on Ubuntu 18.04 doesn't work

### ISSUE THREAD

**Issue by francisglee** [nspies/genomeview#12]
I tried installing `genomeviewer` on a blank Ubuntu 18.04 machine using `pip install genomeview`, and attempted to import the package using:

```python
import genomeviewer
```

I received the following error:

```
ERROR:root:Unable to load cythonized quickconsensus module; this is likely because pysam has been updated since genomeview was originally install. To fix this, force reinstall genomeview: 
  pip install --upgrade --force-reinstall genomeview

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-86a95fc1585c> in <module>
----> 1 import genomeview

~/Documents/amplicon-ngs-workflow/.venv/lib/python3.6/site-packages/genomeview/__init__.py in <module>
     22 from genomeview.axis import *
     23 from genomeview.track import *
---> 24 from genomeview.bamtrack import *
     25 from genomeview.bedtrack import BEDTrack
     26 from genomeview.graphtrack import *

~/Documents/amplicon-ngs-workflow/.venv/lib/python3.6/site-packages/genomeview/bamtrack.py in <module>
      4 from genomeview.track import Track
      5 from genomeview.intervaltrack import Interval, IntervalTrack
----> 6 from genomeview import MismatchCounts
      7 from genomeview.utilities import match_chrom_format
      8 

ImportError: cannot import name 'MismatchCounts'
```
I then tried cloning the git repo into the directory of interest and ran the setup installation using `setup.py`:

```
git clone https://github.com/nspies/genomeview
cd genomeview
python3 setup.py install
```

Now `genomeviewer` can be imported. 

I haven't dug too deeply into this issue, but reinstalling the package as suggested by [this issue](https://github.com/nspies/genomeview/issues/8) didn't solve the problem.

**Comment by nspies** [comment]
I would have to see the install logs to have some chance of figuring out what's going wrong with your install. I believe the reason it's working when you run it locally is that you're not importing the version you installed but rather the version in the cloned directory. If there is no compiled cython version of quickconsensus, it'll fall back on a pure python version (for example, if you downloaded but haven't installed). I would guess that if you change directory to somewhere else, you'll once again get the same error.

If there is a cython version that cannot be imported, genomeview will bail so that you don't accidentally run with the python version which can be vastly slower for error-prone long-read data. If you're not using long-read data, you can probably just use the pure python version without too much of a problem -- just replace import of `genomeview._quickconsensus` with `genomeview.quickconsensus` in [`__init__.py`](https://github.com/nspies/genomeview/blob/master/genomeview/__init__.py#L7).

**Comment by francisglee** [comment]
The install log is printed below:

```bash
ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ python3 -m venv .venv
ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ source .venv/bin/activate
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip install genomeview
Collecting genomeview
  Using cached https://files.pythonhosted.org/packages/81/34/db88cf0c01f9dc78da709e55ae6c7f271608e19f1ec72c851cd85926bf0a/genomeview-1.0.1.tar.gz
Collecting numpy (from genomeview)
  Using cached https://files.pythonhosted.org/packages/f5/bf/4981bcbee43934f0adb8f764a1e70ab0ee5a448f6505bd04a87a2fda2a8b/numpy-1.16.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pysam (from genomeview)
  Using cached https://files.pythonhosted.org/packages/f1/fc/d2be1a093bd8494ab63e3168aca36c2494753bbff190f3201ce2e7da9cda/pysam-0.15.2-cp36-cp36m-manylinux1_x86_64.whl
Building wheels for collected packages: genomeview
  Running setup.py bdist_wheel for genomeview ... error
  Complete output from command /home/ifrancium/Projects/test/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p31xooaj/genomeview/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpo50th_71pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for genomeview
  Running setup.py clean for genomeview
Failed to build genomeview
Installing collected packages: numpy, pysam, genomeview
  Running setup.py install for genomeview ... done
Successfully installed genomeview-1.0.1 numpy-1.16.1 pysam-0.15.2
```

Running `pip freeze`:

```bash
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip freeze
genomeview==1.0.1
numpy==1.16.1
pkg-resources==0.0.0
pysam==0.15.2
```
No `cython` installed.  

Running a quick import test:

```bash
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import genomeview
ERROR:root:Unable to load cythonized quickconsensus module; this is likely because pysam has been updated since genomeview was originally install. To fix this, force reinstall genomeview: 
  pip install --upgrade --force-reinstall genomeview
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ifrancium/Projects/test/.venv/lib/python3.6/site-packages/genomeview/__init__.py", line 24, in <module>
    from genomeview.bamtrack import *
  File "/home/ifrancium/Projects/test/.venv/lib/python3.6/site-packages/genomeview/bamtrack.py", line 6, in <module>
    from genomeview import MismatchCounts
ImportError: cannot import name 'MismatchCounts'
```
I reset the virtual environment and installed `cython` and `genomeview`.  Below is the install log.

```bash
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ deactivate
ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ rm -rf .venv/
ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ ls -alt
total 8
drwxr-xr-x  2 ifrancium ifrancium 4096 Feb  2 22:23 .
drwxr-xr-x 12 ifrancium ifrancium 4096 Feb  2 22:09 ..
ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ python3 -m venv .venv
ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ source .venv/bin/activate
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip freeze
pkg-resources==0.0.0
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip install cython genomeview
Collecting cython
  Using cached https://files.pythonhosted.org/packages/32/a7/05c7796b3a74eb1deab2236f02dfb205af65bb1642cf51865ee20279b86d/Cython-0.29.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting genomeview
  Using cached https://files.pythonhosted.org/packages/81/34/db88cf0c01f9dc78da709e55ae6c7f271608e19f1ec72c851cd85926bf0a/genomeview-1.0.1.tar.gz
Collecting numpy (from genomeview)
  Using cached https://files.pythonhosted.org/packages/f5/bf/4981bcbee43934f0adb8f764a1e70ab0ee5a448f6505bd04a87a2fda2a8b/numpy-1.16.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pysam (from genomeview)
  Using cached https://files.pythonhosted.org/packages/f1/fc/d2be1a093bd8494ab63e3168aca36c2494753bbff190f3201ce2e7da9cda/pysam-0.15.2-cp36-cp36m-manylinux1_x86_64.whl
Building wheels for collected packages: genomeview
  Running setup.py bdist_wheel for genomeview ... error
  Complete output from command /home/ifrancium/Projects/test/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9z8pt5ww/genomeview/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpv4zrmdb1pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for genomeview
  Running setup.py clean for genomeview
Failed to build genomeview
Installing collected packages: cython, numpy, pysam, genomeview
  Running setup.py install for genomeview ... done
Successfully installed cython-0.29.4 genomeview-1.0.1 numpy-1.16.1 pysam-0.15.2
```
`pip freeze` yields:

```bash
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip freeze
Cython==0.29.4
genomeview==1.0.1
numpy==1.16.1
pkg-resources==0.0.0
pysam==0.15.2
```

Quick import test yields the same error:

```bash
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import genomeview
ERROR:root:Unable to load cythonized quickconsensus module; this is likely because pysam has been updated since genomeview was originally install. To fix this, force reinstall genomeview: 
  pip install --upgrade --force-reinstall genomeview
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ifrancium/Projects/test/.venv/lib/python3.6/site-packages/genomeview/__init__.py", line 24, in <module>
    from genomeview.bamtrack import *
  File "/home/ifrancium/Projects/test/.venv/lib/python3.6/site-packages/genomeview/bamtrack.py", line 6, in <module>
    from genomeview import MismatchCounts
ImportError: cannot import name 'MismatchCounts'
>>> 
```
But I can import `cython`:

```bash
>>> import cython
>>> print(cython.__version__)
0.29.4
>>> 
```

**Comment by nspies** [comment]
Hrm, google suggests that this may be due to a missing wheel package. What version of python and pip are you running? Can you try installing wheel and then genomeview?

**Comment by francisglee** [comment]
Alright.  So it turns out that `pip` might be outdated ([see comment](https://github.com/miguelgrinberg/flasky/issues/379#issuecomment-414116225)).  So I updated `pip`.

```bash
ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ python3 -m venv .venv
ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ source .venv/bin/activate
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/46/dc/7fd5df840efb3e56c8b4f768793a237ec4ee59891959d6a215d63f727023/pip-19.0.1-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 469kB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.0.1
```
Python and Pip versions are:

```bash
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ python --version
Python 3.6.7
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip --version
pip 19.0.1 from /home/ifrancium/Projects/test/.venv/lib/python3.6/site-packages/pip (python 3.6)
```

I reinstalled `genomeview` and the wheel error seems to have been resolved.

```
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip install genomeview
Collecting genomeview
  Using cached https://files.pythonhosted.org/packages/81/34/db88cf0c01f9dc78da709e55ae6c7f271608e19f1ec72c851cd85926bf0a/genomeview-1.0.1.tar.gz
Collecting numpy (from genomeview)
  Using cached https://files.pythonhosted.org/packages/f5/bf/4981bcbee43934f0adb8f764a1e70ab0ee5a448f6505bd04a87a2fda2a8b/numpy-1.16.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pysam (from genomeview)
  Using cached https://files.pythonhosted.org/packages/f1/fc/d2be1a093bd8494ab63e3168aca36c2494753bbff190f3201ce2e7da9cda/pysam-0.15.2-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, pysam, genomeview
  Running setup.py install for genomeview ... done
Successfully installed genomeview-1.0.1 numpy-1.16.1 pysam-0.15.2
```

Import test yields the same result however:(

```
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import genomeview
ERROR:root:Unable to load cythonized quickconsensus module; this is likely because pysam has been updated since genomeview was originally install. To fix this, force reinstall genomeview: 
  pip install --upgrade --force-reinstall genomeview
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ifrancium/Projects/test/.venv/lib/python3.6/site-packages/genomeview/__init__.py", line 24, in <module>
    from genomeview.bamtrack import *
  File "/home/ifrancium/Projects/test/.venv/lib/python3.6/site-packages/genomeview/bamtrack.py", line 6, in <module>
    from genomeview import MismatchCounts
ImportError: cannot import name 'MismatchCounts'
>>> quit()
```
I installed `cython` and reinstalled `genomeview`, but the error remains.

```
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip install cython
Collecting cython
  Using cached https://files.pythonhosted.org/packages/32/a7/05c7796b3a74eb1deab2236f02dfb205af65bb1642cf51865ee20279b86d/Cython-0.29.4-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: cython
Successfully installed cython-0.29.4
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip install --upgrade --force-reinstall genomeview
Collecting genomeview
  Using cached https://files.pythonhosted.org/packages/81/34/db88cf0c01f9dc78da709e55ae6c7f271608e19f1ec72c851cd85926bf0a/genomeview-1.0.1.tar.gz
Collecting numpy (from genomeview)
  Using cached https://files.pythonhosted.org/packages/f5/bf/4981bcbee43934f0adb8f764a1e70ab0ee5a448f6505bd04a87a2fda2a8b/numpy-1.16.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pysam (from genomeview)
  Using cached https://files.pythonhosted.org/packages/f1/fc/d2be1a093bd8494ab63e3168aca36c2494753bbff190f3201ce2e7da9cda/pysam-0.15.2-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, pysam, genomeview
  Found existing installation: numpy 1.16.1
    Uninstalling numpy-1.16.1:
      Successfully uninstalled numpy-1.16.1
  Found existing installation: pysam 0.15.2
    Uninstalling pysam-0.15.2:
      Successfully uninstalled pysam-0.15.2
  Found existing installation: genomeview 1.0.1
    Uninstalling genomeview-1.0.1:
      Successfully uninstalled genomeview-1.0.1
  Running setup.py install for genomeview ... done
Successfully installed genomeview-1.0.1 numpy-1.16.1 pysam-0.15.2
```
```bash
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ pip freeze
Cython==0.29.4
genomeview==1.0.1
numpy==1.16.1
pkg-resources==0.0.0
pysam==0.15.2
```
```bash
(.venv) ifrancium@ifrancium-Blade-Stealth:~/Projects/test$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import genomeview
ERROR:root:Unable to load cythonized quickconsensus module; this is likely because pysam has been updated since genomeview was originally install. To fix this, force reinstall genomeview: 
  pip install --upgrade --force-reinstall genomeview
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ifrancium/Projects/test/.venv/lib/python3.6/site-packages/genomeview/__init__.py", line 24, in <module>
    from genomeview.bamtrack import *
  File "/home/ifrancium/Projects/test/.venv/lib/python3.6/site-packages/genomeview/bamtrack.py", line 6, in <module>
    from genomeview import MismatchCounts
ImportError: cannot import name 'MismatchCounts'
>>> 
```

I'll try digging deeper into this tomorrow.  More soon,

**Comment by ehenrion** [comment]
Hi, I noticed the issue's been closed but I'm facing the same issue and was wondering if a solution had been found after all ? came out...

Thanks

**Comment by ehenrion** [comment]
I fixed the import error by updating genomeview/bamtrack.py with `from genomeview.quickconsensus import MismatchCounts` instead of `from genomeview import MismatchCounts`

I still have the error : `ERROR:root:Unable to load cythonized quickconsensus module; this is likely because pysam has been updated since genomeview was originally install. To fix this, force reinstall genomeview: 
  pip install --upgrade --force-reinstall genomeview` 
But it only appears once... it seems genomeview can be loaded after that...
```
>>> import genomeview
ERROR:root:Unable to load cythonized quickconsensus module; this is likely because pysam has been updated since genomeview was originally install. To fix this, force reinstall genomeview: 
  pip install --upgrade --force-reinstall genomeview
>>> import genomeview
```

**Comment by ehenrion** [comment]
Another solution that fixed it all !
First, for the context : I have installed genomeview using pip, and I noticed it always ended up with  no `genomeview/_quickconsensus.pyx` file.
Instead, it creates a `_quickconsensus.cpython-37m-x86_64-linux-gnu.so` file.
So I manually copied the `genomeview/_quickconsensus.pyx` file form your repository into my installation folder...
And now everything works fine ! without having to modify `genomeview/bamtrack.py`
